# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'Playground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Playground

end

#target '手动分配内存' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#
#  # Pods for 手动分配内存
#
#end
